// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoibum4Buq9be517_2v6KzKNRK09GiLvY',
    appId: '1:105879855601:web:7301abfc3818478fc7e450',
    messagingSenderId: '105879855601',
    projectId: 'chandrakalm-b310f',
    authDomain: 'chandrakalm-b310f.firebaseapp.com',
    storageBucket: 'chandrakalm-b310f.firebasestorage.app',
    measurementId: 'G-S9RRJF7S7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArCtnEe450ShdoNbQ3mjNtXF_jBCH99g4',
    appId: '1:105879855601:android:6d8dd7e3daf806c5c7e450',
    messagingSenderId: '105879855601',
    projectId: 'chandrakalm-b310f',
    storageBucket: 'chandrakalm-b310f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymWhq5NYX1lbWy1oqZ4Si4UUZ9Gdzfnw',
    appId: '1:105879855601:ios:549784f6a3d927d0c7e450',
    messagingSenderId: '105879855601',
    projectId: 'chandrakalm-b310f',
    storageBucket: 'chandrakalm-b310f.firebasestorage.app',
    iosBundleId: 'com.techpanda.chandrakalm',
  );
}
